### ISSUE TITLE
some considerations about the code

### ISSUE THREAD

**Issue by andreafdaf** [PulpoWork/angular2-inner-content#1]
Hi!

First of all thanks so much for this directive, it's really strange that something like this is not present in Angular2 since this functionality existed in Angular1 (and maybe if built inside Angular performance could have been optimized)... I was starting to write something like it but then I found your comment on SO :grin:

Anyway:

line 47: let dynComponent = this.toComponent(template, directives)
should be: const dynComponent = this.toComponent(template, directives)
line 51: let component = factory.create(
should be: const component = factory.create(
- those vars are never modified

line 52: this.injector, null, this.elementRef._element.nativeElement
should be: this.injector, null, this.elementRef.element.nativeElement
- this way no errors are thrown by the TS compiler, i guess the "_" var is meant to be "kind of private"

Thanks again, nice job!

PS: do you know if this will last? I had a previous one working using DynamicComponentLoader but it's not usable anymore, hope this one will last!

**Comment by andreafdaf** [comment]
btw I made this PR to save you a couple of minutes #2

**Comment by henrique-rotava** [comment]
Hei!

I'm happy to know it was usefull for you and thanks for your improvements!

Merged!
